services:
  main_app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
      CI: "true"
      REACT_APP_API_URL: "http://localhost:3001"
      WDS_SOCKET_HOST: "0.0.0.0"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    command: sh -c "npm install --legacy-peer-deps && npm start"
